### ISSUE TITLE
Wrong nodes using Branches and Nodes (QGIS)

### ISSUE THREAD

**Issue by brick00** [BjornNyberg/NetworkGT#25]
Hi there!

**QGIS v 3.22**

I am currently working on tracing features on field-images, however I am getting wrong topologies for reasons beyond my understanding. The main issue is that the Branches and Nodes tool (topology) mistakenly puts I nodes where actually there is a Y or an X node (see image). I have tried the repair topology tool, which reduces the problem, but does not completely solve it. At first I tried using GPKG, then I tried to convert GPKG to SHP, and then finally I tried a "fresh start" using pure SHP - same error in every case. CRS is consistent between project and layers. 

Weirdly, nodes for the same network are interpreted correctly using ArcMAP. However, I would like to avoid jumping from a software to the other. I was just wondering wheter it's something to deal with the tool or perhaps it's something wrong with the dataset?
![error](https://user-images.githubusercontent.com/83013730/217555364-3a39a34d-40ff-483f-81c6-0be6fe79bdff.png)

**Comment by BjornNyberg** [comment]
Hi @brick00 

A lot of the time I see these issues related to the coordinate system and number of decimal places used. I also find that this problem is common if converting from ArcMap to QGIS given the higher precision of the latter. Do you have an example that you may be able to share so that I may dive into the issue further?

Cheers,
Björn

**Comment by brick00** [comment]
Hi Bjorn! 

Thanks for replying. 

I think I might have worded my issue wrong. The original project is on QGIS, and the original lines were in a GPKG format. After running Branches and Nodes on QGIS several times using also line networks in SHP format, I noticed that the error was persistent. Therefore I moved to ARC to see whether this would replicate, and I found that the issue disappeared and all nodes were identified correctly. 

Here's another example of what's happening - here the two lines are clearly snapped, however, the node is not correct. Again, i doublechecked whether the coordinated was consistent throughout the project.

I would be happy to share an example, however I am not sure what's the safest way to do that? 

![error2](https://user-images.githubusercontent.com/83013730/217573845-8968d1cc-0008-4911-a661-99d28fc3f633.png)

**Comment by BjornNyberg** [comment]
@brick00 

If you can send me the file to bjorn.nyberg@uib.no that would be ideal.

Cheers,
Björn

**Comment by BjornNyberg** [comment]
Fixed by updating to the latest version.

**Comment by brick00** [comment]
Hi Bjorn. 

I am still having this issue unfortunately.. I really have no clue of what it could be. I went through every single step we discussed the last time we spoke, and nothing is working anymore. Tried to reinstall NetworkGT, but it did not solve it either

I am on 3.22 Białowieża - NetGT 1.0

**Comment by BjornNyberg** [comment]
Hi again @brick00,

I am sorry to hear this is causing you trouble. Can you send an example to me by email so that I may replicate the problem.

Cheers

**Comment by brick00** [comment]
Hey Bjorn!

Thanks for your reply! 😄 just emailed it over to you!

Cheers

**Comment by BjornNyberg** [comment]
For future reference, the issue seemed to be related to the fracture networks not being connected. This issue was solved by using the Trim and Extend tool to extend the fractures that were not connected.
